---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/xl-front-back-app
  type: udm.Application
  children:
  - name: 1.0.83
    type: udm.DeploymentPackage
    orchestrator:
    - sequential-by-deployed
    deployables:
    - name: front
      type: uccm.ContainerSpec
      image: bmoussaud/xl-demo-frontend:1.0.83
      replicas: '{{replicas}}'
      profile: production
      env:
        BACKEND_ENDPOINT: http://back-web-service
        FEATURE: UCCM <b>{{env}}</b>-xl-demo-frontend:1.0.83
      ports:
      - name: web
        type: uccm.ContainerPortSpec
        containerPort: "8000"
        servicePort: "80"
        exposeAsIngress: "true"
      mountedFiles:
      - name: config
        type: uccm.MountedFileSpec
        placeholders:
        - alternate.color
        path: /opt/config/data
        isSensitive: "false"
        file: !file "artifacts/Applications/xl-front-back-app/1.0.83/front/config/config.properties"
      - name: sensitive-config
        type: uccm.MountedFileSpec
        placeholders:
        - password
        path: /opt/config/data_secured
        isSensitive: "true"
        file: !file "artifacts/Applications/xl-front-back-app/1.0.83/front/sensitive-config/secured-config.properties"
    - name: back
      type: uccm.ContainerSpec
      image: bmoussaud/xl-demo-backend:1.0.83
      replicas: "1"
      profile: production
      ports:
      - name: web
        type: uccm.ContainerPortSpec
        containerPort: "8000"
        servicePort: "80"
    - name: uccm test application availability
      type: smoketest.HttpRequestTest
      url: http://xl-demo-{{env}}.xl-front-back-app.xebialabs.demo/
      expectedResponseText: Hello, world!
  - name: 1.0.82
    type: udm.DeploymentPackage
    orchestrator:
    - sequential-by-deployed
    deployables:
    - name: front
      type: uccm.ContainerSpec
      image: bmoussaud/xl-demo-frontend:1.0.82
      replicas: '{{replicas}}'
      profile: production
      env:
        BACKEND_ENDPOINT: http://back-web-service
        FEATURE: UCCM <b>{{env}}</b>-xl-demo-frontend:1.0.82
      ports:
      - name: web
        type: uccm.ContainerPortSpec
        containerPort: "8000"
        servicePort: "80"
        exposeAsIngress: "true"
      mountedFiles:
      - name: config
        type: uccm.MountedFileSpec
        placeholders:
        - alternate.color
        path: /opt/config/data
        isSensitive: "false"
        file: !file "artifacts/Applications/xl-front-back-app/1.0.82/front/config/config.properties"
      - name: sensitive-config
        type: uccm.MountedFileSpec
        placeholders:
        - password
        path: /opt/config/data_secured
        isSensitive: "true"
        file: !file "artifacts/Applications/xl-front-back-app/1.0.82/front/sensitive-config/secured-config.properties"
    - name: back
      type: uccm.ContainerSpec
      image: bmoussaud/xl-demo-backend:1.0.81
      replicas: "1"
      profile: production
      ports:
      - name: web
        type: uccm.ContainerPortSpec
        containerPort: "8000"
        servicePort: "80"
    - name: uccm test application availability
      type: smoketest.HttpRequestTest
      url: http://xl-demo-{{env}}.xl-front-back-app.xebialabs.demo/
      expectedResponseText: Hello, world!
  - name: 1.0.81
    type: udm.DeploymentPackage
    orchestrator:
    - sequential-by-deployed
    deployables:
    - name: uccm test application availability
      type: smoketest.HttpRequestTest
      url: http://xl-demo-{{env}}.xl-front-back-app.xebialabs.demo/
      expectedResponseText: Hello, world!
    - name: front
      type: uccm.ContainerSpec
      image: bmoussaud/xl-demo-frontend:1.0.81
      replicas: '{{replicas}}'
      profile: production
      env:
        BACKEND_ENDPOINT: http://back-web-service
        FEATURE: UCCM <b>{{env}}</b>-xl-demo-frontend:1.0.81
      ports:
      - name: web
        type: uccm.ContainerPortSpec
        containerPort: "8000"
        servicePort: "80"
        exposeAsIngress: "true"
      mountedFiles:
      - name: config
        type: uccm.MountedFileSpec
        placeholders:
        - alternate.color
        path: /opt/config/data
        isSensitive: "false"
        file: !file "artifacts/Applications/xl-front-back-app/1.0.81/front/config/config.properties"
      - name: sensitive-config
        type: uccm.MountedFileSpec
        placeholders:
        - password
        path: /opt/config/data_secured
        isSensitive: "true"
        file: !file "artifacts/Applications/xl-front-back-app/1.0.81/front/sensitive-config/secured-config.properties"
    - name: back
      type: uccm.ContainerSpec
      image: bmoussaud/xl-demo-backend:1.0.81
      replicas: "1"
      profile: production
      ports:
      - name: web
        type: uccm.ContainerPortSpec
        containerPort: "8000"
        servicePort: "80"
  