apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: ECS
  type: core.Directory
  children:
    - name: localhost
      type: overthere.LocalHost
      os: UNIX
      children:
        - name: terraform-client
          type: terraform.TerraformClient
          workingDirectory: '/tmp/pet-aws-tf' # for local installation
          path: '/usr/local/bin' # for local installation

---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: ECS
  type: core.Directory
  children:
    - name: aws-dictionary
      type: udm.Dictionary
      entries:
        AWSRegion: eu-west-1
    - name: AWS
      type: udm.Environment
      members:
      - "~Infrastructure/ECS/localhost/terraform-client"
      dictionaries:
      - "~Environments/ECS/aws-dictionary"