---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: eureka
  type: core.Directory
  children:
  - name: store
    type: udm.Application
    children:
    - name: 1.0.0
      type: udm.DeploymentPackage
      orchestrator:
        - parallel-by-dependency
        - sequential-by-deployed
      applicationDependencies:
        registry: 1.0.0
        product: 1.0.0
        payment: 1.0.0
        invoice: 1.0.0
        notification: 1.0.0
      deployables:
      - name: store-app-db
        type: k8s.ResourcesFile
        file: !file ../databases/mysql.yml
      - name: store-app-service
        type: uccm.ContainerSpec
        image: deepu105/store
        replicas: "1"
        profile: '{{profile}}'
        env:
          SPRING_PROFILES_ACTIVE: prod
          SPRING_CLOUD_CONFIG_URI: http://admin:{{jhipster.registry.password}}@jhipster-registry.xl-demo.svc.cluster.local:8761/config
          EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://admin:{{jhipster.registry.password}}@jhipster-registry.xl-demo.svc.cluster.local:8761/eureka/
          SPRING_DATASOURCE_URL: "jdbc:mysql://store-mysql.xl-demo.svc.cluster.local:3306/store?useUnicode=true&characterEncoding=utf8&useSSL=false"
          SPRING_SLEUTH_PROPAGATION_KEYS: x-request-id,x-ot-span-context
          JAVA_OPTS: -Xmx256m -Xms256m
        securedEnv:
          JHIPSTER_REGISTRY_PASSWORD: x-{{ jhipster.registry.password }}
          SPRING_DATASOURCE_PASSWORD: x-{{ postgresql-password }}
        ports:
        - name: http
          type: uccm.ContainerPortSpec
          containerPort: "8080"
          exposeAsService: True
          exposeAsIngress: True
