---
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- directory: Infrastructure/AsCode
  children:
  - name: host-vm
    type: overthere.SshHost
    os: UNIX
    address: deployit.vm
    username: ubuntu
    password: ubuntu
    children:
    - name: sql-db
      type: sql.PostgreSqlClient
      username: scott
      password: tiger
      databaseName: petclinicDev
      postgreSqlHome: /usr
    - name: testRunner
      type: smoketest.Runner
---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- directory: Environments/Dev/AsCode
  children:
  - name: PetClinic Dictionary
    type: udm.Dictionary
    entries:
      TITLE: '{{title}}'
      title: !value title
      log.FilePath: /dev/null
      log.RootLevel: Debug
      smoke.test.url: http://192.168.99.100/petclinic/index.jsp
      tests2.ExecutedHttpRequestTest.url: '{{smoke.test.url}}'
      provider: kubernetes
  - name: PetClinic DB Dictionary
    type: udm.Dictionary
    entries:
      tomcat.DataSource.driverClassName: com.mysql.jdbc.Driver
      tomcat.DataSource.url: jdbc:mysql://localhost/petclinic
      tomcat.DataSource.username: scott
      tomcat.DataSource.context: petclinic
    encryptedEntries:
      tomcat.DataSource.password: passwor
- name: Environments/Dev/Tomcat-Dev-AsCode
  type: udm.Environment
  members:
  - ~Infrastructure/AsCode/host-vm/sql-db
  - ~Infrastructure/AsCode/host-vm/testRunner
  - ~Infrastructure/AsCode/host-vm
  - ~Infrastructure/AsCode/mykube/dev
  dictionaries:
  - ~Environments/Dev/AsCode/PetClinic Dictionary
  - ~Environments/Dev/AsCode/PetClinic DB Dictionary
