---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: eureka
  type: core.Directory
  children:
  - name: product-db
    type: udm.Application
    children:
    - name: 1.0.0
      type: udm.DeploymentPackage
      deployables:
      - name: product-db
        type: k8s.ResourcesFile
        file: !file ../databases/postgresql.yml
