---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: eureka
  type: core.Directory
  children:
  - name: notification
    type: udm.Application
    children:
    - name: 1.0.0
      type: udm.DeploymentPackage
      orchestrator:
        - sequential-by-deployed
      applicationDependencies:
        registry: 1.0.0
      deployables:
      - name: notification-app-db
        type: k8s.ResourcesFile
        file: !file ../databases/mariadb.yml
      - name: notification-app-service
        type: uccm.ContainerSpec
        image: deepu105/notification
        replicas: "1"
        profile: '{{profile}}'
        env:
          SPRING_PROFILES_ACTIVE: prod
          SPRING_CLOUD_CONFIG_URI: http://admin:{{jhipster.registry.password}}@jhipster-registry.xl-demo.svc.cluster.local:8761/config
          EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://admin:{{jhipster.registry.password}}@jhipster-registry.xl-demo.svc.cluster.local:8761/eureka/
          SPRING_DATASOURCE_URL: jdbc:mariadb://notification-mariadb.xl-demo.svc.cluster.local:3306/notification
          SPRING_DATA_MONGODB_DATABASE: notification
          SPRING_DATA_MONGODB_URI: 'mongodb://notification-mongodb-0.notification-mongodb.xl-demo:27017'
          SPRING_SLEUTH_PROPAGATION_KEYS: x-request-id,x-ot-span-context
          JAVA_OPTS: -Xmx256m -Xms256m
        securedEnv:
          JHIPSTER_REGISTRY_PASSWORD: x-{{ jhipster.registry.password }}
          SPRING_DATASOURCE_PASSWORD: x-{{ mariadb-root-password }}
        ports:
        - name: http
          type: uccm.ContainerPortSpec
          containerPort: "8083"
          exposeAsService: True
